# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simple/Workspace/minecraft/reactor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simple/Workspace/minecraft/reactor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simple/Workspace/minecraft/reactor/CMakeFiles /home/simple/Workspace/minecraft/reactor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simple/Workspace/minecraft/reactor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reactor

# Build rule for target.
reactor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reactor
.PHONY : reactor

# fast build rule for target.
reactor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/build
.PHONY : reactor/fast

#=============================================================================
# Target rules for targets named reactor_debug

# Build rule for target.
reactor_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reactor_debug
.PHONY : reactor_debug

# fast build rule for target.
reactor_debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/build
.PHONY : reactor_debug/fast

src/connection.o: src/connection.c.o
.PHONY : src/connection.o

# target to build an object file
src/connection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/connection.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/connection.c.o
.PHONY : src/connection.c.o

src/connection.i: src/connection.c.i
.PHONY : src/connection.i

# target to preprocess a source file
src/connection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/connection.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/connection.c.i
.PHONY : src/connection.c.i

src/connection.s: src/connection.c.s
.PHONY : src/connection.s

# target to generate assembly for a file
src/connection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/connection.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/connection.c.s
.PHONY : src/connection.c.s

src/packet/reader.o: src/packet/reader.c.o
.PHONY : src/packet/reader.o

# target to build an object file
src/packet/reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/packet/reader.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/packet/reader.c.o
.PHONY : src/packet/reader.c.o

src/packet/reader.i: src/packet/reader.c.i
.PHONY : src/packet/reader.i

# target to preprocess a source file
src/packet/reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/packet/reader.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/packet/reader.c.i
.PHONY : src/packet/reader.c.i

src/packet/reader.s: src/packet/reader.c.s
.PHONY : src/packet/reader.s

# target to generate assembly for a file
src/packet/reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/packet/reader.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/packet/reader.c.s
.PHONY : src/packet/reader.c.s

src/packet/writer.o: src/packet/writer.c.o
.PHONY : src/packet/writer.o

# target to build an object file
src/packet/writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/packet/writer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/packet/writer.c.o
.PHONY : src/packet/writer.c.o

src/packet/writer.i: src/packet/writer.c.i
.PHONY : src/packet/writer.i

# target to preprocess a source file
src/packet/writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/packet/writer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/packet/writer.c.i
.PHONY : src/packet/writer.c.i

src/packet/writer.s: src/packet/writer.c.s
.PHONY : src/packet/writer.s

# target to generate assembly for a file
src/packet/writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/packet/writer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/packet/writer.c.s
.PHONY : src/packet/writer.c.s

src/reactor.o: src/reactor.c.o
.PHONY : src/reactor.o

# target to build an object file
src/reactor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/reactor.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/reactor.c.o
.PHONY : src/reactor.c.o

src/reactor.i: src/reactor.c.i
.PHONY : src/reactor.i

# target to preprocess a source file
src/reactor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/reactor.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/reactor.c.i
.PHONY : src/reactor.c.i

src/reactor.s: src/reactor.c.s
.PHONY : src/reactor.s

# target to generate assembly for a file
src/reactor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/reactor.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/reactor.c.s
.PHONY : src/reactor.c.s

src/util/logger.o: src/util/logger.c.o
.PHONY : src/util/logger.o

# target to build an object file
src/util/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/util/logger.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/util/logger.c.o
.PHONY : src/util/logger.c.o

src/util/logger.i: src/util/logger.c.i
.PHONY : src/util/logger.i

# target to preprocess a source file
src/util/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/util/logger.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/util/logger.c.i
.PHONY : src/util/logger.c.i

src/util/logger.s: src/util/logger.c.s
.PHONY : src/util/logger.s

# target to generate assembly for a file
src/util/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/util/logger.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/util/logger.c.s
.PHONY : src/util/logger.c.s

src/util/unicode_string.o: src/util/unicode_string.c.o
.PHONY : src/util/unicode_string.o

# target to build an object file
src/util/unicode_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/util/unicode_string.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/util/unicode_string.c.o
.PHONY : src/util/unicode_string.c.o

src/util/unicode_string.i: src/util/unicode_string.c.i
.PHONY : src/util/unicode_string.i

# target to preprocess a source file
src/util/unicode_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/util/unicode_string.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/util/unicode_string.c.i
.PHONY : src/util/unicode_string.c.i

src/util/unicode_string.s: src/util/unicode_string.c.s
.PHONY : src/util/unicode_string.s

# target to generate assembly for a file
src/util/unicode_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor.dir/build.make CMakeFiles/reactor.dir/src/util/unicode_string.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_debug.dir/build.make CMakeFiles/reactor_debug.dir/src/util/unicode_string.c.s
.PHONY : src/util/unicode_string.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... reactor"
	@echo "... reactor_debug"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/packet/reader.o"
	@echo "... src/packet/reader.i"
	@echo "... src/packet/reader.s"
	@echo "... src/packet/writer.o"
	@echo "... src/packet/writer.i"
	@echo "... src/packet/writer.s"
	@echo "... src/reactor.o"
	@echo "... src/reactor.i"
	@echo "... src/reactor.s"
	@echo "... src/util/logger.o"
	@echo "... src/util/logger.i"
	@echo "... src/util/logger.s"
	@echo "... src/util/unicode_string.o"
	@echo "... src/util/unicode_string.i"
	@echo "... src/util/unicode_string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

